version: '3'
services:
  tao:
    build: .
    image: local/tao:0.10
    depends_on:
      - database
    ports:
      - "80:80"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tao
      POSTGRES_PASSWORD: tao
      POSTGRES_DB: tao
      TZ: "Europe/Zurich"
